# Generated by Django 2.0.7 on 2018-11-15 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roleprimary', models.CharField(default=None, max_length=100)),
                ('rolesecorndary', models.CharField(default=None, max_length=500)),
                ('availability', models.CharField(choices=[('free', 'Free'), ('semi', 'Semi-Free'), ('busy', 'Busy')], default='Free', max_length=10)),
                ('lookingfor', models.CharField(default=None, max_length=500)),
            ],
        ),
    ]
