# Generated by Django 2.0.7 on 2018-11-15 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userstats_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstats',
            name='lookingfor',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='roleprimary',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='rolesecorndary',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
    ]
