# Generated by Django 2.1 on 2018-08-30 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20180829_2042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='postto',
            new_name='page',
        ),
    ]
