# Generated by Django 2.1 on 2018-08-31 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20180829_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('general', 'General'), ('recommendation', 'Listen to This'), ('recommend me', 'Recommend Me...'), ('shows', 'Live Shows'), ('personal', 'Personal'), ('new music', 'Made This!')], default='general', max_length=20),
        ),
    ]
