# Generated by Django 2.1 on 2018-09-04 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20180903_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='page',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='pages.Page'),
        ),
    ]
