# Generated by Django 2.1 on 2018-09-05 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20180903_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='page',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='pages.Page'),
        ),
    ]
