# Generated by Django 2.0.7 on 2018-09-10 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20180904_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='musicembed',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
    ]
