# Generated by Django 2.0.7 on 2018-09-10 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_post_musicembed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(max_length=2500),
        ),
        migrations.AlterField(
            model_name='post',
            name='musicembed',
            field=models.CharField(default=None, max_length=800, null=True),
        ),
    ]
