# Generated by Django 2.0.7 on 2018-09-10 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20180910_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='musicembed',
            field=models.CharField(default=None, max_length=1500, null=True),
        ),
    ]
