# Generated by Django 2.0.7 on 2018-09-10 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='musicembed',
            field=models.CharField(default=None, max_length=800, null=True),
        ),
    ]
