# Generated by Django 2.0.7 on 2018-09-10 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_page_musicembed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='listening',
        ),
        migrations.AlterField(
            model_name='page',
            name='musicembed',
            field=models.CharField(default=None, max_length=1500, null=True),
        ),
    ]
