# Generated by Django 2.1 on 2018-11-05 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20181105_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='musicembed',
        ),
        migrations.AddField(
            model_name='page',
            name='featured',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
